### ISSUE TITLE
Wrong detection of LOW security ciphers on agents

### ISSUE THREAD

**Issue by maniac777** [brianpardy/em13c#4]
Hi,

To detect low security ciphers on agents you execute:

/usr/bin/openssl s_client -prexit -connect [hostname]3872 -tls1_2 -cipher LOW | /bin/grep Cipher | uniq | /bin/grep -c 0000
and you expect to get "0" because openssl should return something like this:

SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000

It is true when you check for MEDIUM but on Oracle Linux 6.9 there setting -cipher LOW wil get the following result:

error setting cipher list
139744041248584:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1314:

This is because current version of OpenSSL does not support any of ciphers in section low:

$ openssl ciphers LOW
Error in cipher list
140665824761672:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1314:

So this checking method is wrong. Unfortunetly i do not have any proposal for replacement in detection LOW ciphers.

**Comment by brianpardy** [comment]
Hi,

Thank you for reporting this issue. I could add a check for support of LOW strength ciphers in the installed OpenSSL and then skip or fail the test in that case, which I already do for TLSv1.1 and v1.2 on SLES11 where OpenSSL doesn't support them unless you install an optional OpenSSL package with support for the newer protocols.

Would you prefer to see the script just skip tests it cannot perform due to OpenSSL compatibility, or to have it flag those tests and report them at the end with other failed tests?

I'm not sure of any other good way to run this check, and it doesn't make sense to go seek out an OpenSSL config that supports weak ciphers just to run this test. Maybe as another fallback option I can have it identify supported ciphers by checking the config files for each OMS/WLS/console/agent component. I would still prefer to directly test it though. I will look into this and see what I can come up with.

**Comment by brianpardy** [comment]
I have changed the script on the beta branch to run "openssl ciphers LOW" to check for the availability of LOW strength ciphers before running this test.  If it finds no LOW strength ciphers available, the script will log this as a warning to display at the end.

Could you please try testing this update out and let me know how it goes?

[Direct link](https://raw.githubusercontent.com/brianpardy/em13c/beta/checksec13R2.sh)

**Comment by maniac777** [comment]
Hi,

Currently during check phase there is info:

(2) Checking supported ciphers at SSL/TLS endpoints (see notes 2138391.1,
1067411.1)
(2a) Checking LOW strength ciphers on Agent (_HOST_:3872, protocol
tls1_2)...Error in cipher list
140128523298632:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no
cipher match:ssl_lib.c:1314:
FAILED - PERMITS LOW STRENGTH CIPHER CONNECTIONS
(2a) Checking MEDIUM strength ciphers on Agent (_HOST_:3872)... OK
(2a) Checking HIGH strength ciphers on Agent (_HOST:3872)... OK
(...)

And below:

Cleaning up temporary files... done
Failed test count: 73 - Review output

ciphercheck:Agent @ _HOST_:3872:Permits LOW strength ciphers
ciphercheck:BIPublisher @ _HOST_:9803:Permits LOW strength ciphers
ciphercheck:NodeManager @ _HOST_:7403:Permits LOW strength ciphers
(...)



2017-04-25 16:55 GMT+02:00 Brian Pardy <notifications@github.com>:

**Comment by brianpardy** [comment]
Thank you for testing this attempt at a fix.  The extra info coming from OpenSSL there is my fault; it prints the "no cipher match" text to stderr instead of stdout, and I forgot to redirect the output.  I've just pushed a new update to the beta branch that I think will fix it this time so that it parses the OpenSSL output correctly.  Please let me know if it works better for you now.

I will also work on breaking out the summary report at the end to distinguish between warnings like this and failures.  Thanks!

**Comment by brianpardy** [comment]
I believe this issue is now resolved. I will close it in a few days unless I receive a report that it still occurs.

**Comment by sumeerarora** [comment]
Getting the following warning for LOW ciphers, when i execute checksec13R2.sh in my OMS environment

ciphercheck:BIPublisher @ hostname:8903:Unable to check LOW strength ciphers, not supported by installed OpenSSL
ciphercheck:BIPublisher @ hostname:8903:Permits MEDIUM strength ciphers
ciphercheck:NodeManager @ hostname:7703:Unable to check LOW strength ciphers, not supported by installed OpenSSL
ciphercheck:NodeManager @ hostname:7703:Permits MEDIUM strength ciphers

-------------------
My OS version is Oracle Linux Server release 6.10 and i do see a note in the script that there is an issue while running the script on oracle linux 6.9

"# Thanks to Rafał Ramocki, who noted an issue with OpenSSL on Oracle Linux
# 6.9 where OpenSSL does not have LOW strength ciphers available, causing
# an error in the script.
"

Is there a fix for it ?

**Comment by brianpardy** [comment]
Hello,

I do not have access to any Oracle Linux systems, but unless you are able
to install an old version of openssl, there is unfortunately no easy fix
for this problem.  The script used to get an error message from recent
releases of openssl when it attempted to check the LOW strength ciphers -
the message you are seeing from the script indicates that it has tested
your openssl version and determined it does not support LOW strength
ciphers, so it prints out that warning instead of an error from openssl.

Unfortunately if openssl does not support LOW strength ciphers, this script
cannot automatically check if the OEM components are allowing LOW strength
ciphers.  The only way I have found to do this is to find another machine
that has an old version of openssl (or compile and install your own old
version on your OEM server) and then manually run the test from there by
running: "openssl s_client -prexit -connect omshost:port -tls1_2 -cipher
LOW", then reviewing the output for errors.  If you can get an old openssl
on your OEM server, and install it as /usr/bin/openssl1, the script will
choose openssl1 to do the tests.

On SuSE Linux, there is an openssl1 binary available that supports the old
LOW strength ciphers, but the system openssl does not, so I have a
workaround in the script to use that openssl1 binary instead, but I am not
sure if you can find one for OL 6.10.

This is not a good fix, but it is the best I have found.

Good luck!
